spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paas
    username: root
    password: woshizm

mybatis:
  typeAliasesPackage: uk.ac.shef.timetask.mapper
  mapperLocations: classpath:mapper/*Mapper.xml
  configLocation: classpath:mybatis-config.xml
